os:
  - ubuntu/bionic64/csharp-driver
cassandra:
  - dse-5.1
  - dse-6.0
  - dse-6.7
build:
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      export CCM_PATH=$HOME/ccm
      export DSE_INITIAL_IPPREFIX="127.0.0."
      export DSE_BRANCH=$CCM_BRANCH
      export DSE_VERSION=$CCM_VERSION
      export DSE_IN_REMOTE_SERVER="false"
      echo $DSE_VERSION
      echo $DSE_BRANCH
      echo $DSE_PATH
      echo $DSE_INITIAL_IPPREFIX

      echo "==========copying ssl files to $HOME/ssl=========="
      cp -r /home/jenkins/ccm/ssl $HOME/ssl

      # Download and uncompress saxon
      mkdir saxon
      curl -L -o saxon/SaxonHE9-8-0-12J.zip https://downloads.sourceforge.net/project/saxon/Saxon-HE/9.8/SaxonHE9-8-0-12J.zip
      unzip saxon/SaxonHE9-8-0-12J.zip -d saxon

      export DOTNET_CLI_TELEMETRY_OUTPUT=1
      dotnet --version

      # Install the required packages
      echo "==========Install the required packages=========="
      dotnet restore src

      # Run the tests
      echo "==========RUNNING FULL SUITE OF TESTS=========="
      echo "==========RUNNING SUITE OF UNIT TESTS=========="
      dotnet test src/Cassandra.DataStax.Graph.Test.Unit/Cassandra.DataStax.Graph.Test.Unit.csproj -f netcoreapp2.0  -c Release --logger "trx;LogFileName=../../../TestResultUnit.trx"
      echo "==========Transforming unit test result trx file to junit=========="
      java -jar saxon/saxon9he.jar -o:TestResultUnit.xml TestResultUnit.trx tools/trx-to-junit.xslt
      echo "==========RUNNING SUITE OF INTEGRATION TESTS=========="
      dotnet test src/Cassandra.DataStax.Graph.Test.Integration/Cassandra.DataStax.Graph.Test.Integration.csproj -f netcoreapp2.0  -c Release --logger "trx;LogFileName=../../../TestResultIntegration.trx"
      echo "==========Transforming integration test result trx file to junit=========="
      java -jar saxon/saxon9he.jar -o:TestResultIntegration.xml TestResultIntegration.trx tools/trx-to-junit.xslt
  - xunit:
    - "TestResult*.xml"
